// IncrementalGeneratorSkeleton.cs
// Minimal IIncrementalGenerator that emits a Hello.g.cs file.
// Build this in a separate project that targets netstandard2.0 and references
// Microsoft.CodeAnalysis.CSharp; consumers add it as <Analyzer>.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace BackEnd.CSharp.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class HelloGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find every class annotated [GenerateHello]
        var classes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "BackEnd.CSharp.SourceGenerators.GenerateHelloAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Where(static s => s is not null);

        context.RegisterSourceOutput(classes, static (spc, cls) =>
        {
            var ns = cls.ContainingNamespace.IsGlobalNamespace
                ? null
                : cls.ContainingNamespace.ToDisplayString();
            var name = cls.Name;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            if (ns is not null) sb.AppendLine($"namespace {ns};");
            sb.AppendLine($"partial class {name}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static string Hello() => \"Hello from {name}\";");
            sb.AppendLine("}");

            spc.AddSource($"{name}.Hello.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });

        // Always emit the marker attribute
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "GenerateHelloAttribute.g.cs", SourceText.From("""
            namespace BackEnd.CSharp.SourceGenerators;
            [System.AttributeUsage(System.AttributeTargets.Class)]
            internal sealed class GenerateHelloAttribute : System.Attribute { }
            """, Encoding.UTF8)));
    }
}
